import figma from '@figma/code-connect';

import BpkImage from '../../bpk-component-image/src/BpkImage';

import BpkOverlay,{OVERLAY_TYPES} from './BpkOverlay';


/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  BpkOverlay,
  'https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=11552%3A10364',
  {
    props: {
      style: figma.enum('Style', {
        High: OVERLAY_TYPES.solidHigh,
        Medium: OVERLAY_TYPES.solidMedium,
        Low: OVERLAY_TYPES.solidLow,
        None: OVERLAY_TYPES.off,
        '↓ Heavy': OVERLAY_TYPES.heavyBottom,
        '↓ High': OVERLAY_TYPES.bottomHigh,
        '↓ Medium': OVERLAY_TYPES.bottomMedium,
        '↓ Low': OVERLAY_TYPES.bottomLow,
        '↑ Heavy': OVERLAY_TYPES.heavyTop,
        '↑ High': OVERLAY_TYPES.topHigh,
        '↑ Medium': OVERLAY_TYPES.topMedium,
        '↑ Low': OVERLAY_TYPES.topLow,
        '← High': OVERLAY_TYPES.leftHigh,
        '← Medium': OVERLAY_TYPES.leftMedium,
        '← Low': OVERLAY_TYPES.leftLow,
        '→ High': OVERLAY_TYPES.rightHigh,
        '→ Medium': OVERLAY_TYPES.rightMedium,
        '→ Low': OVERLAY_TYPES.rightLow,
        '◻︎ Vignette': OVERLAY_TYPES.vignette,
      }),
    },
    example: ({ style }) => <BpkOverlay overlayType={style}>
      <BpkImage
        altText="altText here"
        aspectRatio={16}
        src="" />
    </BpkOverlay>,
  },
);
