import React from "react"
import BpkBadge, { BADGE_TYPES, BadgeType } from './BpkBadge';
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  BpkBadge,
  "https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=37974%3A344",
  {
    props: {
      style: figma.enum('Style', {
        "Normal": BADGE_TYPES.normal,
        "Success": BADGE_TYPES.success,
        "Warning": BADGE_TYPES.warning,
        "Critical": BADGE_TYPES.critical,
        "Inverse": BADGE_TYPES.inverse,
        "Outline": BADGE_TYPES.outline,
        "Brand": BADGE_TYPES.brand,
        "Strong": BADGE_TYPES.strong
      }),
    },
    example: ({ style }) => <BpkBadge type={style}>My badge</BpkBadge>,
  },
)
