import React from "react"
import BpkBadge from "./BpkBadge"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  BpkBadge,
  "https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=37974%3A344",
  {
    props: {
      // No matching props could be found for these Figma properties:
      "style": figma.enum('Style', {
        "Normal": "normal",
        "Success": "success",
        "Warning": "warning",
        "Critical": "critical",
        "Inverse": "inverse",
        "Outline": "outline",
        "Brand": "brand",
        "Strong": "strong"
      }),
    },
    example: ({ style }) => <BpkBadge type={style}>My badge</BpkBadge>,
  },
)
