import figma from "@figma/code-connect"

import BpkSaveButton, { SIZE_TYPES, STYLE_TYPES } from "./BpkSaveButton"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BpkSaveButton,
  "https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=22719%3A26190",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Default: SIZE_TYPES.default,
        Small: SIZE_TYPES.small,
      }),
      style: figma.enum("Style", {
        Default: STYLE_TYPES.default,
        Contained: STYLE_TYPES.contained,
        "On Dark": STYLE_TYPES.onDark,
      }),
      checked: figma.enum('State', {
        "Saved": true,
      })
    },
    example: ({ checked, size, style }) => (
      <BpkSaveButton
        checked={checked}
        accessibilityLabel="Save"
        onCheckedChange={() => {}}
        size={size}
        style={style}
      />
    ),
  },
)
