# Specification https://skyscanner.atlassian.net/l/cp/U0rFrY7n
version: '1'
type: library
component:
  name: design-system
  awsProjectTag: design-system
  owner:
    - clover
  description: Skyscanner's internal Backpack design system library.
  serviceClass: economy-class
  public: false
  personalDataHandling: none
  soxScope: false
  paymentProcessing: false
  outOfHoursSupportRequired: false
  lifecycleState: production
