packages:
  - 'packages/*'
  - 'libs/*'

overrides:
  braces: 3.0.3

allowBuilds:
  '@parcel/watcher': true
  '@percy/core': true
  '@skyscanner/eslint-config-skyscanner': true
  core-js: true
  esbuild: true
  less: true
  node-sass: false
  nx: true
  unrs-resolver: true

ignoredOptionalDependencies:
  - node-sass

strictPeerDependencies: false

publicHoistPattern:
  - '*eslint*'
  - '*stylelint*'
  - '*prettier*'
