#!/usr/bin/env node
const { spawnSync } = require('child_process');

const [path, ...rest] = process.argv.slice(2);
const [command, ...args] = rest.slice(0);

const result = spawnSync(command, args, { cwd: path, stdio: 'inherit' });

process.exit(result.status);
