#!/usr/bin/env node
const { spawn } = require('child_process');

const [path, ...rest] = process.argv.slice(2);
const [command, ...args] = rest.slice(0);

spawn(command, args, { cwd: path, stdio: 'inherit' });
