import figma from '@figma/code-connect';

import BpkLink from './BpkLink';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BpkLink,
  'https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=54170%3A57',
  {
    props: {
      implicit: figma.enum('Type', {
        Implicit: true,
      }),
      children: figma.string('Text'),
      alternate: figma.enum('Style', {
        "Default": false,
        "On Contrast": true
      }),
    },
    example: ({
      alternate,
      children,
      implicit,
    }) => (
      <BpkLink
        implicit={implicit}
        alternate={alternate}
      >
        {children}
      </BpkLink>
    ),
  },
);
