import figma from '@figma/code-connect';

import BpkLink from './BpkLink';


/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BpkLink,
  'https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=54170%3A57',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      implicit: figma.enum('Type', {
        Implicit: true,
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "On Contrast": "on-contrast",
      //   "Hover": "hover"
      // }),
      // "style": figma.enum('Style', {
      //   "Default": "default",
      //   "On Contrast": "on-contrast"
      // })
    },
    example: ({
      implicit,
    }) => (
      <BpkLink
        implicit={implicit}
      >
        Link
      </BpkLink>
    ),
  },
);
