// flow-typed signature: c27cfe57f5073fdc01508ea638e7c5ba
// flow-typed version: <<STUB>>/tinymask_v1.0.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinymask'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinymask' {
  declare module.exports: any;
}
