export const BUTTON_PADDING_Y = '18px';
export const BUTTON_PADDING_X = '20px';
export const BUTTON_BACKGROUND_COLOR = 'rgb(255, 255, 255)';
export const BUTTON_BACKGROUND_IMAGE = 'none';
export const BUTTON_COLOR = 'rgb(0, 105, 130)';
export const BUTTON_BORDER_RADIUS = 'none';
export const BUTTON_BOX_SHADOW = 'inset 0px 0px 0px 1px #006982';
export const BUTTON_HOVER_BACKGROUND_COLOR = 'rgb(0, 105, 130)';
export const BUTTON_HOVER_COLOR = 'rgb(255, 255, 255)';
export const BUTTON_HOVER_BOX_SHADOW = 'inset 0px 0px 0px 1px rgba(0, 105, 130, 0.33)';
export const BUTTON_DISABLED_BACKGROUND_COLOR = 'rgb(255, 255, 255)';
export const BUTTON_DISABLED_COLOR = 'rgba(0, 105, 130, 0.33)';
export const BUTTON_DISABLED_BOX_SHADOW = 'inset 0px 0px 0px 1px rgba(0, 105, 130, 0.33)';
export const BUTTON_SELECTED_COLOR = 'rgb(255, 255, 255)';
export const BUTTON_SELECTED_BACKGROUND_COLOR = 'rgb(0, 105, 130)';
export const BUTTON_SELECTED_BACKGROUND_IMAGE = 'none';
export const BUTTON_SELECTED_HOVER_COLOR = 'rgb(255, 255, 255)';
export const BUTTON_SELECTED_HOVER_BACKGROUND_COLOR = 'rgb(0, 105, 130)';
export const BUTTON_ACTIVE_BACKGROUND_COLOR = 'rgb(0, 105, 130)';
export const buttons = {
BUTTON_PADDING_Y,
BUTTON_PADDING_X,
BUTTON_BACKGROUND_COLOR,
BUTTON_BACKGROUND_IMAGE,
BUTTON_COLOR,
BUTTON_BORDER_RADIUS,
BUTTON_BOX_SHADOW,
BUTTON_HOVER_BACKGROUND_COLOR,
BUTTON_HOVER_COLOR,
BUTTON_HOVER_BOX_SHADOW,
BUTTON_DISABLED_BACKGROUND_COLOR,
BUTTON_DISABLED_COLOR,
BUTTON_DISABLED_BOX_SHADOW,
BUTTON_SELECTED_COLOR,
BUTTON_SELECTED_BACKGROUND_COLOR,
BUTTON_SELECTED_BACKGROUND_IMAGE,
BUTTON_SELECTED_HOVER_COLOR,
BUTTON_SELECTED_HOVER_BACKGROUND_COLOR,
BUTTON_ACTIVE_BACKGROUND_COLOR,
};