module.exports = {
  buttonPaddingY: "8px",
  buttonPaddingX: "24px",
  buttonPaddingXIconOnly: "1rem",
  buttonBorderRadius: "3px",
  buttonBackgroundColor: "rgb(52, 54, 61)",
  buttonBackgroundImage: "none",
  buttonHoverBackgroundColor: "rgb(77, 80, 89)",
  buttonHoverBackgroundImage: "none",
  buttonActiveBackgroundColor: "rgb(77, 80, 89)",
  buttonActiveBackgroundImage: "none",
  buttonDisabledBackgroundColor: "rgba(0, 0, 0, 0.5)",
  buttonDisabledBackgroundImage: "none",
  buttonColor: "rgb(0, 221, 238)",
  buttonFontWeight: "normal",
  buttonDisabledColor: "rgb(178, 174, 189)",
  buttonFontSize: ".875rem",
  buttonLineHeight: "1.125em",
  buttonTextAlign: "center",
  buttonLargePaddingX: "2rem",
  buttonLargePaddingY: "0.375rem",
  buttonLargePaddingXIconOnly: ".5625rem",
  buttonLargeFontSize: "1rem",
  buttonLargeLineHeight: "1.875rem",
  buttonDisabledBoxShadow: "none",
  buttonSecondaryBackgroundColor: "rgba(0, 0, 0, 0.5)",
  buttonSecondaryBackgroundImage: "none",
  buttonSecondaryHoverBackgroundColor: "rgba(0, 187, 204, 0.2)",
  buttonSecondaryHoverBackgroundImage: "none",
  buttonSecondaryActiveBackgroundColor: "rgba(0, 187, 204, 0.2)",
  buttonSecondaryActiveBackgroundImage: "none",
  buttonSecondaryDisabledBackgroundColor: "rgb(230, 228, 235)",
  buttonSecondaryDisabledBackgroundImage: "none",
  buttonSecondaryColor: "rgb(52, 54, 61)",
  buttonSecondaryHoverColor: "rgb(52, 54, 61)",
  buttonSecondaryActiveColor: "rgb(52, 54, 61)",
  buttonSecondaryBoxShadow: "none",
  buttonSecondaryHoverBoxShadow: "none",
  buttonSecondaryActiveBoxShadow: "none",
  buttonSecondaryDisabledBoxShadow: "none",
  buttonSecondaryFontSize: ".875rem",
  buttonSecondaryFontWeight: "400",
  buttonSecondaryLineHeight: "1.25rem",
  buttonDestructiveFontSize: ".875rem",
  buttonDestructiveLineHeight: "1.25rem",
  buttonDestructiveColor: "rgb(197, 0, 14)",
  buttonDestructiveBoxShadow: "none",
  buttonDestructiveHoverColor: "rgb(197, 0, 14)",
  buttonDestructiveHoverBoxShadow: "none",
  buttonDestructiveActiveColor: "rgb(255, 84, 82)",
  buttonDestructiveActiveBoxShadow: "0 0 0 3px #ff5452 inset",
  buttonDestructiveDisabledBackgroundColor: "rgb(230, 228, 235)",
  buttonDestructiveDisabledBackgroundImage: "none",
  buttonDestructiveDisabledColor: "rgb(178, 174, 189)",
  buttonDestructiveDisabledBoxShadow: "none",
  fontFamilyBase: "'markweb', Helvetica, Arial, sans-serif",
  linkColor: "rgb(0, 187, 204)",
  linkTextDecoration: "none",
  linkHoverColor: "rgb(52, 54, 61)",
  linkHoverTextDecoration: "underline",
  linkActiveColor: "rgb(77, 80, 89)",
  linkWhiteColor: "rgb(255, 255, 255)",
  linkWhiteHoverColor: "rgb(255, 255, 255)",
  linkWhiteActiveColor: "rgb(247, 247, 247)"
};