module.exports = {
  buttonPaddingY: "8px",
  buttonPaddingX: "24px",
  buttonBorderRadius: "3px",
  buttonBackgroundColor: "rgb(52, 54, 61)",
  buttonBackgroundImage: "none",
  buttonHoverBackgroundColor: "rgb(0, 0, 0)",
  buttonHoverBackgroundImage: "none",
  buttonActiveBackgroundColor: "rgb(0, 0, 0)",
  buttonActiveBackgroundImage: "none",
  buttonDisabledBackgroundColor: "rgb(0, 0, 0)",
  buttonDisabledBackgroundImage: "none",
  buttonColor: "rgb(0, 0, 0)",
  buttonDisabledColor: "rgb(0, 0, 0)",
  buttonFontSize: ".875rem",
  buttonFontWeight: "normal",
  buttonLineHeight: "1.125em",
  buttonTextAlign: "center",
  linkColor: "rgb(0, 187, 204)",
  linkTextDecoration: "none",
  linkHoverColor: "rgb(52, 54, 61)",
  linkHoverTextDecoration: "underline",
  linkActiveColor: "rgb(77, 80, 89)",
  linkWhiteColor: "rgb(255, 255, 255)",
  linkWhiteHoverColor: "rgb(255, 255, 255)",
  linkWhiteActiveColor: "rgb(247, 247, 247)"
};