export const BUTTON_PADDING_Y = '8px';
export const BUTTON_PADDING_X = '24px';
export const BUTTON_PADDING_X_ICON_ONLY = '1rem';
export const BUTTON_BORDER_RADIUS = '3px';
export const BUTTON_BACKGROUND_COLOR = 'rgb(52, 54, 61)';
export const BUTTON_BACKGROUND_IMAGE = 'none';
export const BUTTON_HOVER_BACKGROUND_COLOR = 'rgb(77, 80, 89)';
export const BUTTON_HOVER_BACKGROUND_IMAGE = 'none';
export const BUTTON_ACTIVE_BACKGROUND_COLOR = 'rgb(77, 80, 89)';
export const BUTTON_ACTIVE_BACKGROUND_IMAGE = 'none';
export const BUTTON_DISABLED_BACKGROUND_COLOR = 'rgba(0, 0, 0, 0.5)';
export const BUTTON_DISABLED_BACKGROUND_IMAGE = 'none';
export const BUTTON_COLOR = 'rgb(0, 221, 238)';
export const BUTTON_FONT_WEIGHT = 'normal';
export const BUTTON_DISABLED_COLOR = 'rgb(0, 0, 0)';
export const BUTTON_FONT_SIZE = '.875rem';
export const BUTTON_LINE_HEIGHT = '1.125em';
export const BUTTON_TEXT_ALIGN = 'center';
export const BUTTON_LARGE_PADDING_X = '2rem';
export const BUTTON_LARGE_PADDING_Y = '0.375rem';
export const BUTTON_LARGE_PADDING_X_ICON_ONLY = '.5625rem';
export const BUTTON_LARGE_FONT_SIZE = '1rem';
export const BUTTON_LARGE_LINE_HEIGHT = '1.875rem';
export const BUTTON_DISABLED_BOX_SHADOW = 'none';
export const BUTTON_SECONDARY_BACKGROUND_COLOR = 'rgba(0, 0, 0, 0.5)';
export const BUTTON_SECONDARY_BACKGROUND_IMAGE = 'none';
export const BUTTON_SECONDARY_HOVER_BACKGROUND_COLOR = 'rgba(0, 187, 204, 0.2)';
export const BUTTON_SECONDARY_HOVER_BACKGROUND_IMAGE = 'none';
export const BUTTON_SECONDARY_ACTIVE_BACKGROUND_COLOR = 'rgba(0, 187, 204, 0.2)';
export const BUTTON_SECONDARY_ACTIVE_BACKGROUND_IMAGE = 'none';
export const BUTTON_SECONDARY_DISABLED_BACKGROUND_COLOR = 'rgb(0, 0, 0)';
export const BUTTON_SECONDARY_DISABLED_BACKGROUND_IMAGE = 'none';
export const BUTTON_SECONDARY_COLOR = 'rgb(52, 54, 61)';
export const BUTTON_SECONDARY_HOVER_COLOR = 'rgb(52, 54, 61)';
export const BUTTON_SECONDARY_ACTIVE_COLOR = 'rgb(52, 54, 61)';
export const BUTTON_SECONDARY_BOX_SHADOW = 'none';
export const BUTTON_SECONDARY_HOVER_BOX_SHADOW = 'none';
export const BUTTON_SECONDARY_ACTIVE_BOX_SHADOW = 'none';
export const BUTTON_SECONDARY_DISABLED_BOX_SHADOW = 'none';
export const BUTTON_SECONDARY_FONT_SIZE = '.875rem';
export const BUTTON_SECONDARY_FONT_WEIGHT = '400';
export const BUTTON_SECONDARY_LINE_HEIGHT = '1.25rem';
export const BUTTON_DESTRUCTIVE_FONT_SIZE = '.875rem';
export const BUTTON_DESTRUCTIVE_LINE_HEIGHT = '1.25rem';
export const BUTTON_DESTRUCTIVE_COLOR = 'rgb(197, 0, 14)';
export const BUTTON_DESTRUCTIVE_BOX_SHADOW = 'none';
export const BUTTON_DESTRUCTIVE_HOVER_COLOR = 'rgb(197, 0, 14)';
export const BUTTON_DESTRUCTIVE_HOVER_BOX_SHADOW = 'none';
export const BUTTON_DESTRUCTIVE_ACTIVE_COLOR = 'rgb(0, 0, 0)';
export const BUTTON_DESTRUCTIVE_ACTIVE_BOX_SHADOW = '0 0 0 3px {!RED_500} inset';
export const BUTTON_DESTRUCTIVE_DISABLED_BACKGROUND_COLOR = 'rgb(0, 0, 0)';
export const BUTTON_DESTRUCTIVE_DISABLED_BACKGROUND_IMAGE = 'none';
export const BUTTON_DESTRUCTIVE_DISABLED_COLOR = 'rgb(0, 0, 0)';
export const BUTTON_DESTRUCTIVE_DISABLED_BOX_SHADOW = 'none';
export const FONT_FAMILY_BASE = ''markweb', Helvetica, Arial, sans-serif';
export const LINK_COLOR = 'rgb(0, 187, 204)';
export const LINK_TEXT_DECORATION = 'none';
export const LINK_HOVER_COLOR = 'rgb(52, 54, 61)';
export const LINK_HOVER_TEXT_DECORATION = 'underline';
export const LINK_ACTIVE_COLOR = 'rgb(77, 80, 89)';
export const LINK_WHITE_COLOR = 'rgb(255, 255, 255)';
export const LINK_WHITE_HOVER_COLOR = 'rgb(255, 255, 255)';
export const LINK_WHITE_ACTIVE_COLOR = 'rgb(247, 247, 247)';
export const buttons = {
BUTTON_PADDING_Y,
BUTTON_PADDING_X,
BUTTON_PADDING_X_ICON_ONLY,
BUTTON_BORDER_RADIUS,
BUTTON_BACKGROUND_COLOR,
BUTTON_BACKGROUND_IMAGE,
BUTTON_HOVER_BACKGROUND_COLOR,
BUTTON_HOVER_BACKGROUND_IMAGE,
BUTTON_ACTIVE_BACKGROUND_COLOR,
BUTTON_ACTIVE_BACKGROUND_IMAGE,
BUTTON_DISABLED_BACKGROUND_COLOR,
BUTTON_DISABLED_BACKGROUND_IMAGE,
BUTTON_COLOR,
BUTTON_FONT_WEIGHT,
BUTTON_DISABLED_COLOR,
BUTTON_FONT_SIZE,
BUTTON_LINE_HEIGHT,
BUTTON_TEXT_ALIGN,
BUTTON_LARGE_PADDING_X,
BUTTON_LARGE_PADDING_Y,
BUTTON_LARGE_PADDING_X_ICON_ONLY,
BUTTON_LARGE_FONT_SIZE,
BUTTON_LARGE_LINE_HEIGHT,
BUTTON_DISABLED_BOX_SHADOW,
BUTTON_SECONDARY_BACKGROUND_COLOR,
BUTTON_SECONDARY_BACKGROUND_IMAGE,
BUTTON_SECONDARY_HOVER_BACKGROUND_COLOR,
BUTTON_SECONDARY_HOVER_BACKGROUND_IMAGE,
BUTTON_SECONDARY_ACTIVE_BACKGROUND_COLOR,
BUTTON_SECONDARY_ACTIVE_BACKGROUND_IMAGE,
BUTTON_SECONDARY_DISABLED_BACKGROUND_COLOR,
BUTTON_SECONDARY_DISABLED_BACKGROUND_IMAGE,
BUTTON_SECONDARY_COLOR,
BUTTON_SECONDARY_HOVER_COLOR,
BUTTON_SECONDARY_ACTIVE_COLOR,
BUTTON_SECONDARY_BOX_SHADOW,
BUTTON_SECONDARY_HOVER_BOX_SHADOW,
BUTTON_SECONDARY_ACTIVE_BOX_SHADOW,
BUTTON_SECONDARY_DISABLED_BOX_SHADOW,
BUTTON_SECONDARY_FONT_SIZE,
BUTTON_SECONDARY_FONT_WEIGHT,
BUTTON_SECONDARY_LINE_HEIGHT,
BUTTON_DESTRUCTIVE_FONT_SIZE,
BUTTON_DESTRUCTIVE_LINE_HEIGHT,
BUTTON_DESTRUCTIVE_COLOR,
BUTTON_DESTRUCTIVE_BOX_SHADOW,
BUTTON_DESTRUCTIVE_HOVER_COLOR,
BUTTON_DESTRUCTIVE_HOVER_BOX_SHADOW,
BUTTON_DESTRUCTIVE_ACTIVE_COLOR,
BUTTON_DESTRUCTIVE_ACTIVE_BOX_SHADOW,
BUTTON_DESTRUCTIVE_DISABLED_BACKGROUND_COLOR,
BUTTON_DESTRUCTIVE_DISABLED_BACKGROUND_IMAGE,
BUTTON_DESTRUCTIVE_DISABLED_COLOR,
BUTTON_DESTRUCTIVE_DISABLED_BOX_SHADOW,
};
export const typesettings = {
FONT_FAMILY_BASE,
};
export const textColors = {
LINK_COLOR,
LINK_HOVER_COLOR,
LINK_ACTIVE_COLOR,
LINK_WHITE_COLOR,
LINK_WHITE_HOVER_COLOR,
LINK_WHITE_ACTIVE_COLOR,
};
export const textDecorations = {
LINK_TEXT_DECORATION,
LINK_HOVER_TEXT_DECORATION,
};