import React from "react"
import BpkCardWrapper from "./BpkCardWrapper"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  BpkCardWrapper,
  "https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=22618%3A28743",
  {
    props: {},
    example: (props) => (
      <BpkCardWrapper
        card={/* TODO */}
        backgroundColor={/* TODO */}
        header={/* TODO */}
      />
    ),
  },
)
