import React from "react"
import BpkCard from "./BpkCard"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  BpkCard,
  "https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=4395%3A2506",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Focused": "focused"
      // })
    },
    example: (props) => <BpkCard />,
  },
)
