import React from "react"
import BpkCard from "./BpkCard"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  BpkCard,
  "https://www.figma.com/design/jgi6YqueUZ2XnsPsJBhCPw/Untitled?node-id=23-23&m=dev",
  {
    props: {
      children: figma.instance('Content Slot'),
      padded: figma.enum('padded', {
        'base': true,
        'none': false,
      })

    },
    example: ({ children, padded }) => <BpkCard padded={padded}>
      {children}
    </BpkCard>,
  },
)
