import React from "react"
import BpkPanel from "./BpkPanel"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BpkPanel,
  "https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=13418%3A18351",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      keyline: figma.boolean("Keyline?"),
    },
    example: (props) => <BpkPanel keyline={props.keyline} />,
  },
)
