
import figma from "@figma/code-connect"

import BpkStar from "../../bpk-component-star-rating/src/BpkStar";

import BpkRating from "./BpkRating"
import { RATING_SIZES } from './common-types';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BpkRating,
  "https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=7986%3A7639",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Large: RATING_SIZES.large,
        Default: RATING_SIZES.base,
      }),
      "ratingProvider": figma.enum('Rating provider', {
        "Trip Advisor": "trip-advisor",
        "Trip.com": "trip-com",
        "Stars": <BpkStar />,
      }),
      title: figma.textContent("Review"),
      subtitle: figma.textContent("Count"),
      // "arrangement": figma.enum('Arrangement', {
      //   "Title only": "title-only",
      //   "Title • Subtitle": "title---subtitle"
      // })
    },
    example: (props) => (
      <BpkRating ariaLabel={/* TODO */} size={props.size} value={/* TODO */} />
    ),
  },
)
