/*
 * Backpack - Skyscanner's Design System
 *
 * Copyright 2016 Skyscanner Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// AUTO-GENERATED by scripts/generate-figma-connect.js - do not edit manually.

// eslint-disable-next-line import/no-unresolved
import figma from 'figma'

const example = figma.code`
  <${figma.batch.name} />
`

export default {
  id: figma.batch.id,
  variant: { [figma.batch.variantProp]: figma.batch.variantValue },
  example,
  imports: [
    `import ${figma.batch.name} from '${figma.batch.importPath}';`,
  ],
}
