import type { ReactNode } from 'react';
export type Props = {
    id: string;
    children: ReactNode;
    wide?: boolean;
    isIphone: boolean;
    showHeader?: boolean;
    fullScreenOnMobile?: boolean;
    fullScreen?: boolean;
    padded?: boolean;
    dialogRef: (ref: HTMLElement | null | undefined) => void;
    onClose?: () => void;
    className?: string | null;
    contentClassName?: string | null;
    title?: string | null;
    closeLabel?: string;
    closeText?: string | null;
    accessoryView?: ReactNode;
};
declare const BpkModalInner: ({ isIphone, id, dialogRef, children, title, onClose, className, contentClassName, closeLabel, closeText, wide, showHeader, fullScreenOnMobile, fullScreen, padded, accessoryView, ...rest }: Props) => JSX.Element;
export default BpkModalInner;
