/*
 * Backpack - Skyscanner's Design System
 *
 * Copyright 2016 Skyscanner Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import figma from '@figma/code-connect';

import BpkCheckbox from './BpkCheckbox';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BpkCheckbox,
  'https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=30442%3A60450',
  {
    props: {
      state: figma.enum('State', {
        "Checked": true,
        "Disabled": true,
        "Error": null,
        "Indeterminate": false,
        "Not checked": false,
      }),
      label: figma.textContent('Prefer directs'),
      name: figma.textContent('prefer-directs'),
      white: figma.enum('Background', {
        "On dark background": true,
      }),
      onChange : () => {}
    },
    example: ({label, name, onChange, state, white}) => (
      <BpkCheckbox
        name={name}
        label={label}
        checked={state}
        onChange={onChange}
        white={white}
      />
    ),
  },
);
