#!/usr/bin/env node

/*
 * Backpack - Skyscanner's Design System
 *
 * Copyright 2016 Skyscanner Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const { promisify } = require('util');
const { exec } = require('child_process');

const execAsync = promisify(exec);

const command = 'git --no-pager diff --name-only HEAD~1';


const init = async () => {
  const { stdout, stderr } = await execAsync(command, {
    cwd: process.cwd(),
  });

  if (stderr) {
    throw new Error(stderr);
  }

  const changedFiles = stdout
    .trim()
    .split('\n')
    .filter(file => file.endsWith('README.md'));

  if (changedFiles.length) {
    isChanged = true;
    return;
  }

  isChanged = false;
  return;
};

init().then(
  isChanged => console.log(isChanged)
  );