import figma from '@figma/code-connect';

import BpkCarousel from './BpkCarousel';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

const imageList = [
  <img src="https://content.skyscnr.com/m/51c4c9dd04c8dc95/original/Carousel-placeholder-1.jpg" alt="" />,
  <img src="https://content.skyscnr.com/m/7470cf6a4ee49c26/original/Carousel-placeholder-4.jpg" alt="" />,
  <img src="https://content.skyscnr.com/m/f8b42e98e2b79a6/original/Carousel-placeholder-3.jpg" alt="" />,
  <img src="https://content.skyscnr.com/m/183e7ddaaca13b16/original/Carousel-placeholder-2.jpg" alt="" />,
]
figma.connect(
  BpkCarousel,
  'https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=27887%3A32585',
  {
    props: {},
    example: () => (
      <BpkCarousel
        images={imageList}
        initialImageIndex={2}
        onImageChanged={() => null}
      />
    ),
  },
);
