import React from "react"
import BpkSelectableChip from "./BpkSelectableChip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BpkSelectableChip,
  "https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=6730%3A6807",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      dismissible: figma.enum("Type", {
        Dismissible: true,
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      selected: figma.enum("Type", {
        Selectable: true,
      }),
      name: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "style": figma.enum('Style', {
      //   "Default": "default",
      //   "On Dark": "on-dark",
      //   "On Image": "on-image"
      // }),
      // "icon": figma.boolean('Icon')
    },
    example: (props) => (
      <BpkSelectableChip
        dismissible={props.dismissible}
        accessibilityLabel={/* TODO */}
        disabled={props.disabled}
        selected={props.selected}
        onClick={/* TODO */}
        name={props.name}
      />
    ),
  },
)
